/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mtn_atm;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Idrisse_Rose
 */
public class Panel_2 extends javax.swing.JPanel implements ActionListener{


       static String titre_panel;
   static int choi_du_lang2;
  static JFrame frame_2;
   int x=1 ;
    int x_end=5;
    Timer tm;
      static  String welcome_label_string;  
    public Panel_2() {
        initComponents();
        Panel_1.f.setVisible(false);
        
      
        frame_2 = new JFrame("MTN_ATM");
     frame_2.setLocationRelativeTo(null);
     frame_2.setResizable(false);
     frame_2.setLocation(380, 80);
     frame_2.setDefaultCloseOperation(0);
        frame_2.add(this);
        frame_2.setVisible(true);
        frame_2.pack();
        enter_button.setEnabled(false);
        proof1.setVisible(false);
        check.setVisible(false);
        proof2.setVisible(false);
        tm = new Timer(2,this);
    }

    public void paintComponent(Graphics g)
    { super.paintComponent(g);
        tm.start();
     try {
         
        g.setFont(new Font("Times new roman",Font.BOLD,70));
        g.setColor(Color.WHITE);
        g.drawString(welcome_label_string, x,80);
       // Thread.sleep(5);
         }catch(Exception e){}
     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Panel_login = new javax.swing.JPanel();
        proof1 = new javax.swing.JLabel();
        ac_number = new javax.swing.JTextField();
        proof2 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        passWord = new javax.swing.JLabel();
        account_no = new javax.swing.JLabel();
        check = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        back_buton = new javax.swing.JButton();
        enter_button = new javax.swing.JButton();
        cancel1_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Idrisse_Rose\\Documents\\NetBeansProjects\\MTN_ATM\\MTN_Atm.png")); // NOI18N

        Panel_login.setBackground(new java.awt.Color(255, 255, 51));
        Panel_login.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true)));

        proof1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        proof1.setForeground(java.awt.Color.red);
        proof1.setText("");

        ac_number.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ac_number.setForeground(new java.awt.Color(0, 0, 204));
        ac_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ac_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ac_numberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ac_numberKeyTyped(evt);
            }
        });

        proof2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        proof2.setForeground(java.awt.Color.red);
        proof2.setText("");

        Password.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 204));
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordMouseEntered(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordKeyTyped(evt);
            }
        });

        passWord.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        passWord.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passWord.setText("");

        account_no.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        account_no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account_no.setText("");

        check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mtn_atm/images-2.jpeg"))); // NOI18N

        javax.swing.GroupLayout Panel_loginLayout = new javax.swing.GroupLayout(Panel_login);
        Panel_login.setLayout(Panel_loginLayout);
        Panel_loginLayout.setHorizontalGroup(
            Panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account_no))
                .addGap(18, 18, 18)
                .addGroup(Panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ac_number)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_loginLayout.createSequentialGroup()
                        .addComponent(proof1)
                        .addGap(18, 18, 18)
                        .addComponent(check))
                    .addComponent(proof2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_loginLayout.setVerticalGroup(
            Panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(Panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(account_no)
                        .addComponent(ac_number)
                        .addComponent(proof1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passWord)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proof2))
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        back_buton.setBackground(new java.awt.Color(153, 0, 102));
        back_buton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        back_buton.setForeground(new java.awt.Color(255, 255, 255));
        back_buton.setText("");
        back_buton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_butonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_butonMouseExited(evt);
            }
        });
        back_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_butonActionPerformed(evt);
            }
        });
        jPanel2.add(back_buton);

        enter_button.setBackground(new java.awt.Color(153, 0, 102));
        enter_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        enter_button.setForeground(new java.awt.Color(255, 255, 255));
        enter_button.setText("");
        enter_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enter_buttonMouseExited(evt);
            }
        });
        enter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(enter_button);

        cancel1_button.setBackground(new java.awt.Color(153, 0, 102));
        cancel1_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cancel1_button.setForeground(new java.awt.Color(255, 255, 255));
        cancel1_button.setText("");
        cancel1_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel1_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel1_buttonMouseExited(evt);
            }
        });
        cancel1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(cancel1_button);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addComponent(Panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ac_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_numberKeyReleased
        Password.setEnabled(true);
        proof1.setText(null);
        proof2.setVisible(false);
        check.setVisible(false);
        
    }//GEN-LAST:event_ac_numberKeyReleased

    private void ac_numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_numberKeyTyped
        char c2 = evt.getKeyChar();
        if((c2<'0') || (c2>'9') && (c2!= KeyEvent.VK_BACKSPACE))
        evt.consume();

        if (ac_number.getText().length()>=6)
        {     evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_ac_numberKeyTyped

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
       // connection_with_db();
    }//GEN-LAST:event_PasswordMouseClicked

    private void PasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseEntered
     
    }//GEN-LAST:event_PasswordMouseEntered

    private void PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyReleased
        if (Password.getText().length()>=4)
        { enter_button.setEnabled(true);}
        else
        enter_button.setEnabled(false);

    }//GEN-LAST:event_PasswordKeyReleased

    private void PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyTyped
        char c1 = evt.getKeyChar();
        if((c1<'0') || (c1>'9') && (c1!= KeyEvent.VK_BACKSPACE))
        evt.consume();

        if (Password.getText().length()>=4)
        {     evt.consume();
            getToolkit().beep();
        }
        proof2.setVisible(false);
    }//GEN-LAST:event_PasswordKeyTyped

    private void back_butonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_butonMouseEntered
        back_buton.setBackground(Color.GREEN);
    }//GEN-LAST:event_back_butonMouseEntered

    private void back_butonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_butonMouseExited
        back_buton.setBackground(Color.decode("#990066"));
    }//GEN-LAST:event_back_butonMouseExited

    private void back_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_butonActionPerformed
        frame_2.setVisible(false);
        new Panel_1();
    }//GEN-LAST:event_back_butonActionPerformed

    private void enter_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_buttonMouseEntered
        enter_button.setBackground(Color.GREEN);
    }//GEN-LAST:event_enter_buttonMouseEntered

    private void enter_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_buttonMouseExited
        enter_button.setBackground(Color.decode("#990066"));
    }//GEN-LAST:event_enter_buttonMouseExited

    private void enter_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_buttonActionPerformed
        connection_with_db ();


//      try {
//           Connection_function();  
//           rs_faisal = st.executeQuery("select * from Faisal_Bank;");
//           rs_khartoum = st.executeQuery("select * from Khartoum_Bank;");
//         
//           while(rs_khartoum.next())
//               {
//                if(rs_khartoum.getInt("Account_number")== Integer.parseInt(ac_number.getText().trim()))
//                  {
//                    System.out.println("Account_number="+rs_khartoum.getInt("Account_number"));
//                    System.out.println("Name="+rs_khartoum.getString("Name"));
////                  System.out.println("PassWord="+rs_khartoum.getInt("PassWord"));
//                    account_number = rs_khartoum.getInt("Account_number");
//    
//                    if(rs_khartoum.getInt("PassWord")==Integer.parseInt(Password.getText().trim()))
//                       {
////                         System.out.println("PassWord de moga ="+rs_khartoum.getInt("Password"));
//                         System.out.println("this client can access");
//                         
//                         this.setVisible(false);
//                         int balance = rs_khartoum.getInt("Balance");
//                         new Panel_3("Khartoum Bank",account_number,balance);
//                        }
//                    else 
//                        {
//                            
//                        }
//                    }     
//               }
//            while(rs_faisal.next())
//               {
//                if(rs_faisal.getInt("Account_number")== Integer.parseInt(ac_number.getText().trim()))
//                  {
////                    System.out.println("Account_number="+rs_khartoum.getInt("Account_number"));
////                    System.out.println("Name="+rs_khartoum.getString("Name"));
////                    System.out.println("PassWord="+rs_khartoum.getInt("PassWord"));
//                      account_number = rs_faisal.getInt("Account_number");
//                    if(rs_faisal.getInt("PassWord")==Integer.parseInt(Password.getText().trim()))
//                       {
////                         System.out.println("PassWord de moga ="+rs_khartoum.getInt("Password"));
//                         System.out.println("this client can access");
//                         frame_2.setVisible(false);
//                         int balance = rs_faisal.getInt("Balance");
//                         new Panel_3("Faisal Bank",account_number,balance);
//
//                        }
//                    }     
//               }
//       }catch(Exception eeee){System.out.println(eeee);}

    }//GEN-LAST:event_enter_buttonActionPerformed

    private void cancel1_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel1_buttonMouseEntered
        cancel1_button.setBackground(Color.GREEN);
    }//GEN-LAST:event_cancel1_buttonMouseEntered

    private void cancel1_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel1_buttonMouseExited
        cancel1_button.setBackground(Color.decode("#990066"));
    }//GEN-LAST:event_cancel1_buttonMouseExited

    private void cancel1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1_buttonActionPerformed
              int test = JOptionPane.showConfirmDialog(null,"Are you sure to close ?","WARNING",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(test==JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_cancel1_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Panel_login;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField ac_number;
    public static javax.swing.JLabel account_no;
    public static javax.swing.JButton back_buton;
    public static javax.swing.JButton cancel1_button;
    private javax.swing.JLabel check;
    public static javax.swing.JButton enter_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel passWord;
    public static javax.swing.JLabel proof1;
    public static javax.swing.JLabel proof2;
    // End of variables declaration//GEN-END:variables


    Connection con;
    ResultSet rs_1,rs_2, rs_faisal,rs_khartoum;
    ResultSet rs_f , rs_kh;
    Statement st ;
    static int  account_number=0;
    String Bank_name=null;
    
   
public void connection_with_db ()
{
    int test_kh=0,test_f=0;
    int t_f=0;
    int t_kh=0;
    try 
    {      
        if(ac_number.getText().equals(""))
           {
                proof1.setVisible(true);
                Password.setEnabled(false);               
           }
    else
    {
        Connection_function();
         rs_faisal=st.executeQuery("select * from Faisal_Bank;");
         rs_khartoum=st.executeQuery("select * from Khartoum_Bank;");
         
            while(rs_khartoum.next() )
       {
         
                 if(rs_khartoum.getInt("Account_number") == Integer.parseInt(ac_number.getText().trim()))
              {       
                  
                  check.setVisible(true);
                 test_kh=1;
                     rs_kh=st.executeQuery("select Password from Khartoum_Bank;");
                    while(rs_kh.next())
                     {
                        if(rs_kh.getInt("Password")== Integer.parseInt(Password.getText().trim()))
                            { 
                             
                             t_kh=1;                            
                              Panel_3.account_number=rs_khartoum.getInt("Account_number");
                              account_number = rs_khartoum.getInt("Account_number");
                              Bank_name="Khartoum Bank";
                              //Panel_3.BankName=Bank_name;
                            }
                      }
                
              if(t_kh==1)
              {  
                  frame_2.setVisible(false);
                  int balance = rs_khartoum.getInt("Balance");
                  new Panel_3("Khartoum Bank",account_number,balance); } 
         
            }
       }    
            
             while(rs_faisal.next() )
            {
                if(rs_faisal.getInt("Account_number") == Integer.parseInt(ac_number.getText()))
              {                   
                     check.setVisible(true);
                     test_f=1;
                     rs_f=st.executeQuery("select Password from Faisal_Bank;");
                    while(rs_f.next())
                     {
                        if(rs_f.getInt("Password")== Integer.parseInt(Password.getText().trim()))
                            {                              
                             t_f=1;                            
                             account_number=rs_faisal.getInt("Account_number"); 
                             Bank_name="Faisal Bank"; 
                            }
                      }
                
              if(t_f==1)
              {  frame_2.setVisible(false);  
                 //new Panel_3(Bank_name,account_number); 
                int balance = rs_faisal.getInt("Balance");
                new Panel_3("Faisal Bank",account_number,balance);}
                 
              } 
                
                
            }
    if((test_kh+test_f)==0)
    {             if(back_buton.getText().equalsIgnoreCase("Retour"))
                proof1.setText("N'existe pas");
                
                if(back_buton.getText().equalsIgnoreCase("Back"))
                proof1.setText("does not exist");
                
                if(back_buton.getText().equalsIgnoreCase("رجوع"))
                proof1.setText("غير موجود");
                
                   proof1.setVisible(true);
                   Password.setEnabled(false);
        }
    
    if((t_kh+t_f)==0)
        proof2.setVisible(true);
    
    
    
    }  
//  rs_f.close();
//rs_kh.close();
//  con.close();
    }
    catch(Exception ee){System.out.println(ee);}
}





public void Connection_function()
{try {
    con = DriverManager.getConnection("jdbc:ucanaccess://Mtn_Atm_DB.mdb");
   // Class.forName("com.mysql.jdbc.Driver");
   // con = DriverManager.getConnection("jdbc:mysql://localhost/mtn_atm_db","root","root");
    st = con.createStatement();
      
}catch(Exception eee){System.out.println(eee);}
}

    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            if (x<0 || x>=275)
                x_end = -x_end;
           
            x+=x_end;
            
            repaint();
        
           }catch(Exception et){}
        }
        
    


}
