/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mtn_atm;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Idrisse_Rose
 */
public class Panel_3_2 extends javax.swing.JPanel {

    /**
     * Creates new form Panel_3_2
     */
    
     int choi_de_lang=0;
     JFrame frame_3_2 ;
    static String BankName;
    static int  account_number;
    static int  current_balance;
    public Panel_3_2(String Bank_Name, int  accountnumber, int balance) {
        initComponents();
        BankName = Bank_Name;
        account_number =   accountnumber ;
        current_balance = balance;
    
        frame_3_2 = new JFrame("MTN_ATM");
        frame_3_2.setSize(597,540);
        frame_3_2.setVisible(true);
        frame_3_2.setResizable(false);
        frame_3_2.add(this);
       Panel_code_3_2.setVisible(false);
       frame_3_2.setDefaultCloseOperation(0);
      
       frame_3_2.setLocationRelativeTo(null);
       Generate_Button.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_3_2 = new javax.swing.JPanel();
        Generate_Button = new javax.swing.JButton();
        compteur_number = new javax.swing.JTextField();
        counter_number = new javax.swing.JLabel();
        credit_number = new javax.swing.JTextField();
        kilo_de_electricite = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        choi_d_achat2_Button = new javax.swing.JButton();
        finish_3_2_Button = new javax.swing.JButton();
        bank_name1 = new javax.swing.JLabel();
        Panel_code_3_2 = new javax.swing.JPanel();
        code_no_label = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField(8);
        T2 = new javax.swing.JTextField(5);
        T3 = new javax.swing.JTextField(5);
        T4 = new javax.swing.JTextField(5);
        T5 = new javax.swing.JTextField(5);
        T6 = new javax.swing.JTextField(5);
        T7 = new javax.swing.JTextField(8);

        setBackground(new java.awt.Color(255, 0, 102));

        jPanel3.setBackground(new java.awt.Color(255, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Idrisse_Rose\\Documents\\NetBeansProjects\\MTN_ATM\\MTN_Atm.png")); // NOI18N

        Panel_3_2.setBackground(new java.awt.Color(255, 255, 51));
        Panel_3_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));

        Generate_Button.setBackground(new java.awt.Color(153, 0, 102));
        Generate_Button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Generate_Button.setForeground(new java.awt.Color(255, 255, 255));
        Generate_Button.setText("");
        Generate_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Generate_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Generate_ButtonMouseExited(evt);
            }
        });
        Generate_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generate_ButtonActionPerformed(evt);
            }
        });

        compteur_number.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        compteur_number.setForeground(new java.awt.Color(0, 0, 204));
        compteur_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        compteur_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                compteur_numberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                compteur_numberKeyTyped(evt);
            }
        });

        counter_number.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        counter_number.setText("");

        credit_number.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        credit_number.setForeground(new java.awt.Color(0, 0, 204));
        credit_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        credit_number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                credit_numberMouseClicked(evt);
            }
        });
        credit_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                credit_numberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                credit_numberKeyTyped(evt);
            }
        });

        kilo_de_electricite.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        kilo_de_electricite.setText("");

        javax.swing.GroupLayout Panel_3_2Layout = new javax.swing.GroupLayout(Panel_3_2);
        Panel_3_2.setLayout(Panel_3_2Layout);
        Panel_3_2Layout.setHorizontalGroup(
            Panel_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_3_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kilo_de_electricite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(counter_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(compteur_number, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(credit_number))
                .addGap(18, 18, 18)
                .addComponent(Generate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        Panel_3_2Layout.setVerticalGroup(
            Panel_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_3_2Layout.createSequentialGroup()
                .addGroup(Panel_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_3_2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compteur_number, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(counter_number, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(credit_number, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kilo_de_electricite, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_3_2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Generate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));

        choi_d_achat2_Button.setBackground(new java.awt.Color(153, 0, 102));
        choi_d_achat2_Button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        choi_d_achat2_Button.setForeground(new java.awt.Color(255, 255, 255));
        choi_d_achat2_Button.setText("");
        choi_d_achat2_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choi_d_achat2_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choi_d_achat2_ButtonMouseExited(evt);
            }
        });
        choi_d_achat2_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choi_d_achat2_ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(choi_d_achat2_Button);

        finish_3_2_Button.setBackground(new java.awt.Color(153, 0, 102));
        finish_3_2_Button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        finish_3_2_Button.setForeground(new java.awt.Color(255, 255, 255));
        finish_3_2_Button.setText("");
        finish_3_2_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finish_3_2_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                finish_3_2_ButtonMouseExited(evt);
            }
        });
        finish_3_2_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_3_2_ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(finish_3_2_Button);

        bank_name1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bank_name1.setForeground(new java.awt.Color(255, 255, 255));
        bank_name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bank_name1.setText("");

        Panel_code_3_2.setBackground(new java.awt.Color(255, 255, 51));
        Panel_code_3_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));

        code_no_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        code_no_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        code_no_label.setText(" ");

        T1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        T1.setForeground(new java.awt.Color(0, 0, 255));
        T1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        T2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        T2.setForeground(new java.awt.Color(0, 0, 255));
        T2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        T3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        T3.setForeground(new java.awt.Color(0, 0, 255));
        T3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        T4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        T4.setForeground(new java.awt.Color(0, 0, 255));
        T4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        T5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        T5.setForeground(new java.awt.Color(0, 0, 255));
        T5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        T6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        T6.setForeground(new java.awt.Color(0, 0, 255));
        T6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        T7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        T7.setForeground(new java.awt.Color(0, 0, 255));
        T7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout Panel_code_3_2Layout = new javax.swing.GroupLayout(Panel_code_3_2);
        Panel_code_3_2.setLayout(Panel_code_3_2Layout);
        Panel_code_3_2Layout.setHorizontalGroup(
            Panel_code_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_code_3_2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(code_no_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel_code_3_2Layout.setVerticalGroup(
            Panel_code_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_code_3_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_code_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_code_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Panel_code_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Panel_code_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(code_no_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_3_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_code_3_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(bank_name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(71, 71, 71))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bank_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Panel_code_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(441, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Generate_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Generate_ButtonMouseEntered
        Generate_Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_Generate_ButtonMouseEntered

    private void Generate_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Generate_ButtonMouseExited
        Generate_Button.setBackground(Color.decode("#990066"));
    }//GEN-LAST:event_Generate_ButtonMouseExited

    private void Generate_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generate_ButtonActionPerformed
        Panel_code_3_2.setVisible(true);
        T1.setVisible(false); T2.setVisible(false);
        T3.setVisible(false); T4.setVisible(false);
        T5.setVisible(false); T6.setVisible(false);
        T7.setVisible(false);
        this.setSize(597,560);
        if(credit_number.getText().equals("") || Integer.parseInt(credit_number.getText())<=0 ||
            Integer.parseInt(credit_number.getText())<10 || Integer.parseInt(credit_number.getText())>2000 )
        {
            T1.setVisible(false); T2.setVisible(false);
            T3.setVisible(false); T4.setVisible(false);
            T5.setVisible(false); T6.setVisible(false);
            T7.setVisible(false);
            if(choi_d_achat2_Button.getText().equalsIgnoreCase("Retour"))
            code_no_label.setText(" Entrer un Montant entre 10 et 2000");
            if(choi_d_achat2_Button.getText().equalsIgnoreCase("Back"))
            code_no_label.setText("Enter an Amount between 10 and 2000");
            if(choi_d_achat2_Button.getText().equalsIgnoreCase("رجوع"))
            code_no_label.setText("دخل كمية بين  10 و 2000");
        }
        else
        {

            transaction_mtn_with_bank ();  }
        code_no_label.setForeground(Color.blue);
        Generate_Button.setEnabled(false);
    }//GEN-LAST:event_Generate_ButtonActionPerformed

    private void compteur_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_compteur_numberKeyReleased
   credit_number.setText(null);
    }//GEN-LAST:event_compteur_numberKeyReleased

    private void compteur_numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_compteur_numberKeyTyped
        char c1 = evt.getKeyChar();
        if((c1<'0') || (c1>'9') && (c1!= com.sun.glass.events.KeyEvent.VK_BACKSPACE))
        evt.consume();

        if (compteur_number.getText().length()>=11)
        {     evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_compteur_numberKeyTyped

    private void credit_numberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_credit_numberMouseClicked
        if(compteur_number.getText().isEmpty())
        {  credit_number.setText(null); credit_number.setEnabled(false);}
        else  credit_number.setEnabled(true);
    }//GEN-LAST:event_credit_numberMouseClicked

    private void credit_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_credit_numberKeyReleased
 Generate_Button.setEnabled(true);
    }//GEN-LAST:event_credit_numberKeyReleased

    private void credit_numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_credit_numberKeyTyped
        char c2 = evt.getKeyChar();
        if((c2<'0') || (c2>'9') && (c2!= KeyEvent.VK_BACK_SPACE))
        evt.consume();

        if (credit_number.getText().length()>=4)
        {     evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_credit_numberKeyTyped

    private void choi_d_achat2_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choi_d_achat2_ButtonMouseEntered
        choi_d_achat2_Button.setBackground(Color.green);
    }//GEN-LAST:event_choi_d_achat2_ButtonMouseEntered

    private void choi_d_achat2_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choi_d_achat2_ButtonMouseExited
        choi_d_achat2_Button.setBackground(Color.decode("#990066"));
    }//GEN-LAST:event_choi_d_achat2_ButtonMouseExited

    private void choi_d_achat2_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choi_d_achat2_ButtonActionPerformed
        frame_3_2.setVisible(false);
        new Panel_3(BankName,account_number,balance);
        
        if(choi_d_achat2_Button.getText().equalsIgnoreCase("Retour"))
        {  Panel_3.cancel2_Button.setText("Annuler");   Panel_3.choi_de_l_achat.setText("Choisissez ce que vous voulez acheter !!"); Panel_3.credit_Button.setText("Credit MTN"); Panel_3.electric_Button.setText("Achat du courant "); choi_de_lang=1;}

        if(choi_d_achat2_Button.getText().equalsIgnoreCase("Back"))
        {  Panel_3.cancel2_Button.setText("Cancel");    Panel_3.choi_de_l_achat.setText("Choose what you need to buy !!"); Panel_3.credit_Button.setText(" MTN credit"); Panel_3.electric_Button.setText("buying electric ");  choi_de_lang=2;}

        if(choi_d_achat2_Button.getText().equalsIgnoreCase("رجوع"))
        {  Panel_3.cancel2_Button.setText("الغاء");     Panel_3.choi_de_l_achat.setText("ماذا  ترغب ان تشتري !!"); Panel_3.credit_Button.setText("رصيد اريبا"); Panel_3.electric_Button.setText("كهرباء دفع مقدم"); choi_de_lang=3;}
    }//GEN-LAST:event_choi_d_achat2_ButtonActionPerformed

    private void finish_3_2_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finish_3_2_ButtonMouseEntered
        finish_3_2_Button.setBackground(Color.green);
    }//GEN-LAST:event_finish_3_2_ButtonMouseEntered

    private void finish_3_2_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finish_3_2_ButtonMouseExited
        finish_3_2_Button.setBackground(Color.decode("#990066"));
    }//GEN-LAST:event_finish_3_2_ButtonMouseExited

    private void finish_3_2_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish_3_2_ButtonActionPerformed
        new Panel_4();
        frame_3_2.setVisible(false);
        if(finish_3_2_Button.getText().equalsIgnoreCase("Terminer"))
        {   Panel_4.reçu_et_bye_ye.setText("\tW I T H D R A W L \n\n Numero du compte :  "+account_number+"\n Montant: "+credit_number.getText()+" "
                    + " \n Credit: "+balance+" \n\t A bientot");
            Panel_4.finish_Button.setText("Quitter");
        }

        if(finish_3_2_Button.getText().equalsIgnoreCase("Finish"))
        {  Panel_4.reçu_et_bye_ye.setText("\tW I T H D R A W L \n\n Account number :  "+account_number+"\n AMOUNT: "+credit_number.getText()+" "
                    + " \n BALANCE: "+balance+" \n\t See you  ");
            Panel_4.finish_Button.setText("Exit");
        }

        if(finish_3_2_Button.getText().equalsIgnoreCase("انهاء"))
         Panel_4.reçu_et_bye_ye.setText("\tW I T H D R A W L \n\n رقم الحساب :  "+account_number+"\n كمية: "+credit_number.getText()+" "
                    + " \n رصيد: "+balance+" \n\t الي اللقاء");
        Panel_4.finish_Button.setText("خروج");
    }//GEN-LAST:event_finish_3_2_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Generate_Button;
    public static javax.swing.JPanel Panel_3_2;
    private javax.swing.JPanel Panel_code_3_2;
    private javax.swing.JTextField T1;
    public static javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    public static javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    public static javax.swing.JLabel bank_name1;
    public static javax.swing.JButton choi_d_achat2_Button;
    public static javax.swing.JLabel code_no_label;
    private javax.swing.JTextField compteur_number;
    public static javax.swing.JLabel counter_number;
    private javax.swing.JTextField credit_number;
    public static javax.swing.JButton finish_3_2_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel kilo_de_electricite;
    // End of variables declaration//GEN-END:variables

       
public void act(){
String code1=null;String code2=null;String code3=null;
String code4=null;String code5=null;String code6=null;String code7=null;
        	
     for(int j=0;j<=100;j++)
     {         for(int i=1;i<=9;i++)
        	code1=(10+(int)( Math.random()*89))+"";
        	
        	for(int i=1;i<=9;i++)
        	code2=(10+(int)( Math.random()*89))+"";
        	
        	for(int i=1;i<=9;i++)
        	code3=(10+(int)( Math.random()*90))+"";
        	
        	for(int i=1;i<=9;i++)
        	code4=(10+(int)( Math.random()*89))+"";
                
                for(int i=1;i<=9;i++)
        	code5=(10+(int)( Math.random()*90))+"";
        	
        	for(int i=1;i<=9;i++)
        	code6=(10+(int)( Math.random()*90))+"";
        	
        	for(int i=1;i<=9;i++)
        	code7=(10+(int)( Math.random()*90))+"";
     }  	
        T1.setText(code1);T2.setText(code2);T3.setText(code3);
        T4.setText(code4);T5.setText(code5);T6.setText(code6);T7.setText(code7);
            
         code_no_label.setText(null); 
          T1.setVisible(true); T2.setVisible(true);
          T3.setVisible(true); T4.setVisible(true);
          T5.setVisible(true); T6.setVisible(true);
          T7.setVisible(true);
           if(choi_d_achat2_Button.getText().equalsIgnoreCase("Retour"))
       code_no_label.setText("Code du courant :-");
       if(choi_d_achat2_Button.getText().equalsIgnoreCase("Back"))
       code_no_label.setText("Electricity code :-");  
       if(choi_d_achat2_Button.getText().equalsIgnoreCase("رجوع"))
        code_no_label.setText("كود الكهرباء");   

}

    Connection con;
    ResultSet rs_f,rs_kh;
    Statement st , st_2;
    static int balance =0;
  // static int account_number;
   static String Bank_Name;
public void  transaction_mtn_with_bank ()
{
 try {
   
       con = DriverManager.getConnection("jdbc:ucanaccess://Mtn_Atm_DB.mdb");
       
       st = con.createStatement();
       st_2 = con.createStatement();
      
        if(Bank_Name.equalsIgnoreCase("Faisal Bank"))
    {
         rs_f = st.executeQuery("select * from Faisal_Bank where Account_number = "+account_number+" ;");
         System.out.println("1er etape");
         while(rs_f.next())
            {    
             if(rs_f.getInt("Balance") >= Integer.parseInt(credit_number.getText().trim()))
             {    balance = rs_f.getInt("Balance") - Integer.parseInt(credit_number.getText().trim());                
                  act();
                 int test = st_2.executeUpdate("update Faisal_Bank set Balance ="+balance+" where Account_number = "+account_number+";" );                
             }else reponse_negative_transfert();

            }
    }
        
                if(Bank_Name.equalsIgnoreCase("Khartoum Bank"))
    {
         rs_kh = st.executeQuery("select * from Khartoum_Bank where Account_number = "+account_number+" ;");
         System.out.println("1er etape");
         while(rs_kh.next())
            {    
             if(rs_kh.getInt("Balance") >= Integer.parseInt(credit_number.getText()))
             {    balance = rs_kh.getInt("Balance") - Integer.parseInt(credit_number.getText());                
                  act();
                 
                 int test = st_2.executeUpdate("update Khartoum_Bank set Balance ="+balance+" where Account_number = "+account_number+";" );                
             }else reponse_negative_transfert();

            }
    }
 rs_kh.close();
 rs_f.close();
 con.close();
 }
 catch(Exception er)
 {
//     JOptionPane.showMessageDialog(null,"An exception has occured"+er);
     System.out.println(er);
 }
}

    public void reponse_negative_transfert()
{
             
       if(choi_d_achat2_Button.getText().equalsIgnoreCase("Retour"))
       code_no_label.setText("Votre credit est inferieur que ce que voulez ");
       if(choi_d_achat2_Button.getText().equalsIgnoreCase("Back"))
       code_no_label.setText("your balance is less than the electricity that you need");  
       if(choi_d_achat2_Button.getText().equalsIgnoreCase("رجوع"))
        code_no_label.setText("نقودك اقل من الكهرباء الذي طلبته");  
}

}
