/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mtn_atm;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Idrisse_Rose
 */
public class Panel_3_1 extends javax.swing.JPanel {

    /**
     * Creates new form Panel_3_1
     */
    int choi_de_lang=0;
    static int  account_number;
    static int  courant_consome;
    static String BankName;
    static int  current_balance;
    
    
    static JFrame frame_3_1;
    Timer  t ;
     int ii=0;
    public Panel_3_1(String Bank_Name, int  accountnumber, int balance) {
        initComponents();
        BankName = Bank_Name;
        account_number =   accountnumber ;
        current_balance = balance;
        
        frame_3_1 = new JFrame("MTN_ATM");
        Generate_Button.setEnabled(true);
        frame_3_1.setSize(557,550);       
        frame_3_1.setVisible(true);      
        frame_3_1.setResizable(false);
        frame_3_1.setDefaultCloseOperation(0);
        frame_3_1.add(this);
        jPanel5.setVisible(false);
        jb1.setStringPainted(true);
        jb1.setVisible(false);
        jb1.setBorderPainted(true);
        jb1.setForeground( new Color(153, 0, 0));
        jb1.setBackground(Color.WHITE);
        montant_credi.setEnabled(false);
        progression_bar_function();
          
        frame_3_1.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bank_name1 = new javax.swing.JLabel();
        jPanel_credit = new javax.swing.JPanel();
        Generate_Button = new javax.swing.JButton();
        phone_number = new javax.swing.JTextField();
        no_phone_button = new javax.swing.JLabel();
        montant_credi = new javax.swing.JTextField();
        montant_button = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jb1 = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        message_envoi = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        choi_d_achat1_Button = new javax.swing.JButton();
        finish_3_1_Button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Idrisse_Rose\\Documents\\NetBeansProjects\\MTN_ATM\\MTN_Atm.png")); // NOI18N

        bank_name1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        bank_name1.setForeground(new java.awt.Color(255, 255, 255));
        bank_name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bank_name1.setText("");

        jPanel_credit.setBackground(new java.awt.Color(255, 255, 51));
        jPanel_credit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        Generate_Button.setBackground(new java.awt.Color(153, 0, 102));
        Generate_Button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Generate_Button.setForeground(new java.awt.Color(255, 255, 255));
        Generate_Button.setText("");
        Generate_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Generate_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Generate_ButtonMouseExited(evt);
            }
        });
        Generate_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generate_ButtonActionPerformed(evt);
            }
        });

        phone_number.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        phone_number.setForeground(new java.awt.Color(0, 0, 204));
        phone_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phone_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phone_numberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_numberKeyTyped(evt);
            }
        });

        no_phone_button.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        no_phone_button.setText("");

        montant_credi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        montant_credi.setForeground(new java.awt.Color(0, 0, 204));
        montant_credi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        montant_credi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                montant_crediMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                montant_crediMousePressed(evt);
            }
        });
        montant_credi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                montant_crediKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montant_crediKeyTyped(evt);
            }
        });

        montant_button.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        montant_button.setText("montant du credit");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Idrisse_Rose\\Documents\\NetBeansProjects\\MTN_ATM\\ok.png"));

        javax.swing.GroupLayout jPanel_creditLayout = new javax.swing.GroupLayout(jPanel_credit);
        jPanel_credit.setLayout(jPanel_creditLayout);
        jPanel_creditLayout.setHorizontalGroup(
            jPanel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_creditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(montant_button, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(no_phone_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phone_number, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(montant_credi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(Generate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_creditLayout.setVerticalGroup(
            jPanel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_creditLayout.createSequentialGroup()
                .addGroup(jPanel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_creditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(no_phone_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(montant_credi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(montant_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_creditLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Generate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        message_envoi.setFont(new java.awt.Font("Times New Roman", 1, 20));
        message_envoi.setForeground(new java.awt.Color(0, 0, 255));
        message_envoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message_envoi.setText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(message_envoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(message_envoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        choi_d_achat1_Button.setBackground(new java.awt.Color(153, 0, 102));
        choi_d_achat1_Button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        choi_d_achat1_Button.setForeground(new java.awt.Color(255, 255, 255));
        choi_d_achat1_Button.setText("");
        choi_d_achat1_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choi_d_achat1_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choi_d_achat1_ButtonMouseExited(evt);
            }
        });
        choi_d_achat1_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choi_d_achat1_ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(choi_d_achat1_Button);

        finish_3_1_Button.setBackground(new java.awt.Color(153, 0, 102));
        finish_3_1_Button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        finish_3_1_Button.setForeground(new java.awt.Color(255, 255, 255));
        finish_3_1_Button.setText("Finish"
            + "");
        finish_3_1_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finish_3_1_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                finish_3_1_ButtonMouseExited(evt);
            }
        });
        finish_3_1_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_3_1_ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(finish_3_1_Button);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(bank_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bank_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel_credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Generate_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Generate_ButtonMouseEntered
        Generate_Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_Generate_ButtonMouseEntered

    private void Generate_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Generate_ButtonMouseExited
        Generate_Button.setBackground(Color.decode("#990066"));
    }//GEN-LAST:event_Generate_ButtonMouseExited

    private void Generate_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generate_ButtonActionPerformed
        message_envoi.setText(null);
        jPanel5.setVisible(true);

        if(montant_credi.getText().equals("") || Integer.parseInt(montant_credi.getText())<10 || Integer.parseInt(montant_credi.getText())>2000 )
        {
            if(choi_d_achat1_Button.getText().equalsIgnoreCase("Retour"))
            message_envoi.setText(" Entrez un Montant entre 10 et 2000");
            if(choi_d_achat1_Button.getText().equalsIgnoreCase("Back"))
            message_envoi.setText("Enter an Amount between 10 and 2000");
            if(choi_d_achat1_Button.getText().equalsIgnoreCase("رجوع"))
            message_envoi.setText("دخل كمية بين  10 و 2000");
        }
        else
        {  frame_3_1.setSize(500, 588); ii=0; t.start();  
            transaction_mtn_with_bank ();
        }

    }//GEN-LAST:event_Generate_ButtonActionPerformed

    private void phone_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_numberKeyReleased
        jPanel5.setVisible(false);

    }//GEN-LAST:event_phone_numberKeyReleased

    private void phone_numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_numberKeyTyped
        char c2 = evt.getKeyChar();
        if((c2<'0') || (c2>'9') && (c2!= KeyEvent.VK_BACK_SPACE))
        evt.consume();

        if (phone_number.getText().length()>=10)
        {     evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_phone_numberKeyTyped

    private void montant_crediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_montant_crediMouseClicked
        int t=1;
        message_envoi.setText(null);
        if(phone_number.getText().isEmpty() || phone_number.getText().length()<10 )
        { montant_credi.setEnabled(false);
            message_envoi.setText(null);
            jPanel5.setVisible(true);

            if(choi_d_achat1_Button.getText().equalsIgnoreCase("Retour"))
            message_envoi.setText("Entrez un numero mtn  ou bien il n est pas  complet ");
            if(choi_d_achat1_Button.getText().equalsIgnoreCase("Back"))
            message_envoi.setText("Enter a mtn number or it is not complet");
            if(choi_d_achat1_Button.getText().equalsIgnoreCase("رجوع"))
            message_envoi.setText("دخل رقم اريبا  او هذا الرقم غير مكتمل ");
        }

        char c0, c1, c2;
        c0=phone_number.getText().charAt(0);
        c1=phone_number.getText().charAt(1);
         int test=1;

        if((c0=='0') && (c1=='9'))
        {
            c2=phone_number.getText().charAt(2);
          
            if((c2=='2'))
            {  montant_credi.setEnabled(true); test=0; montant_credi.setEditable(true);}

            if((c2=='9'))
            { montant_credi.setEnabled(true);test=0; montant_credi.setEditable(true);}
            
          
            
            if(test==1) 
            no_mtn_number();

        }
        else {no_mtn_number();}
        
        

    }//GEN-LAST:event_montant_crediMouseClicked

    private void montant_crediMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_montant_crediMousePressed

    }//GEN-LAST:event_montant_crediMousePressed

    private void montant_crediKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montant_crediKeyReleased

    }//GEN-LAST:event_montant_crediKeyReleased

    private void montant_crediKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montant_crediKeyTyped

        char c2 = evt.getKeyChar();
        if((c2<'0') || (c2>'9') && (c2!= KeyEvent.VK_BACK_SPACE))
        evt.consume();

        if (montant_credi.getText().length()>=4)
        {     evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_montant_crediKeyTyped

    private void choi_d_achat1_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choi_d_achat1_ButtonMouseEntered
        choi_d_achat1_Button.setBackground(Color.GREEN);;
    }//GEN-LAST:event_choi_d_achat1_ButtonMouseEntered

    private void choi_d_achat1_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choi_d_achat1_ButtonMouseExited
        choi_d_achat1_Button.setBackground(Color.decode("#990066"));
    }//GEN-LAST:event_choi_d_achat1_ButtonMouseExited

    private void choi_d_achat1_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choi_d_achat1_ButtonActionPerformed
        frame_3_1.setVisible(false);
        new Panel_3(BankName,account_number,balance);
        if(choi_d_achat1_Button.getText().equalsIgnoreCase("Retour"))
        {  Panel_3.cancel2_Button.setText("Annuler");   Panel_3.choi_de_l_achat.setText("Choisissez ce que vous voulez acheter !!"); Panel_3.credit_Button.setText("Credit MTN"); Panel_3.electric_Button.setText("Eléctricité "); choi_de_lang=1;}

        if(choi_d_achat1_Button.getText().equalsIgnoreCase("Back"))
        {  Panel_3.cancel2_Button.setText("Cancel");    Panel_3.choi_de_l_achat.setText("Choose what you need to buy !!"); Panel_3.credit_Button.setText(" MTN credit"); Panel_3.electric_Button.setText("buying electricity ");  choi_de_lang=2;}

        if(choi_d_achat1_Button.getText().equalsIgnoreCase("ادخال"))
        {  Panel_3.cancel2_Button.setText("الغاء");     Panel_3.choi_de_l_achat.setText("ماذا  ترغب ان تشتري !!"); Panel_3.credit_Button.setText("رصيد اريبا"); Panel_3.electric_Button.setText("كهرباء"); choi_de_lang=3;}
    }//GEN-LAST:event_choi_d_achat1_ButtonActionPerformed

    private void finish_3_1_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finish_3_1_ButtonMouseEntered
        finish_3_1_Button.setBackground(Color.green);
    }//GEN-LAST:event_finish_3_1_ButtonMouseEntered

    private void finish_3_1_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finish_3_1_ButtonMouseExited
        finish_3_1_Button.setBackground(Color.decode("#990066"));
    }//GEN-LAST:event_finish_3_1_ButtonMouseExited

    private void finish_3_1_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish_3_1_ButtonActionPerformed
        new Panel_4();
        frame_3_1.setVisible(false);
        if(finish_3_1_Button.getText().equalsIgnoreCase("Terminer"))
        {  //Panel_4.reçu_et_bye_ye.setText("Merci d effectuer vos services \n  avec nous  MTN_ATM \n \t A bientot");
            Panel_4.finish_Button.setText("Quitter");
            Panel_4.reçu_et_bye_ye.setText("\tW I T H D R A W L \n\n Numero du compte :  "+account_number+"\n Montant: "+montant_credi.getText()
                    + "eléctricité \n Credit: "+balance+" \n\t A bientot");
            
        }

        if(finish_3_1_Button.getText().equalsIgnoreCase("Finish"))
        { // Panel_4.reçu_et_bye_ye.setText("Thanks to do your services \n  with us  MTN_ATM \n \t See you later");
            Panel_4.finish_Button.setText("Exit");
             Panel_4.reçu_et_bye_ye.setText("\tW I T H D R A W L \n\n Account number :  "+account_number+"\n AMOUNT: "+montant_credi.getText()
                    + "electricity \n BALANCE: "+balance+" \n\t See you  ");
         
        }

        if(finish_3_1_Button.getText().equalsIgnoreCase("انهاء"))
        {//Panel_4.reçu_et_bye_ye.setText("شكرا لاجاز خدماتكم  \n   معنا  MTN_ATM \n \t الي اللقاء");
            Panel_4.finish_Button.setText("خروج");
               Panel_4.reçu_et_bye_ye.setText("\tW I T H D R A W L \n\n رقم الحساب :  "+account_number+"\n كمية: "+montant_credi.getText()+" "
                    + " \n رصيد: "+balance+" \n\t الي اللقاء");
        }
    }//GEN-LAST:event_finish_3_1_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Generate_Button;
    public static javax.swing.JLabel bank_name1;
    public static javax.swing.JButton choi_d_achat1_Button;
    public static javax.swing.JButton finish_3_1_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel jPanel_credit;
    private javax.swing.JProgressBar jb1;
    public static javax.swing.JLabel message_envoi;
    public static javax.swing.JLabel montant_button;
    private javax.swing.JTextField montant_credi;
    public static javax.swing.JLabel no_phone_button;
    private javax.swing.JTextField phone_number;
    // End of variables declaration//GEN-END:variables

    public void reponse_positive_transfert()
{
             
       if(choi_d_achat1_Button.getText().equalsIgnoreCase("Retour"))
       message_envoi.setText(montant_credi.getText()+" SDG est Transfere successivement au "+phone_number.getText());
       if(choi_d_achat1_Button.getText().equalsIgnoreCase("Back"))
       message_envoi.setText(montant_credi.getText()+" SDG has succefully transfered to "+phone_number.getText());  
       if(choi_d_achat1_Button.getText().equalsIgnoreCase("رجوع"))
        message_envoi.setText("تم تحويل الرصيد   "+montant_credi.getText()+"  جنيه  الي  الرقم    "+phone_number.getText());  
}
 

    public void reponse_negative_transfert()
{
             
       if(choi_d_achat1_Button.getText().equalsIgnoreCase("Retour"))
       message_envoi.setText("Transfert non reusi ..votre credit est petit que ce que voulez ");
       if(choi_d_achat1_Button.getText().equalsIgnoreCase("Back"))
       message_envoi.setText("no transfert ..your balance is less than the credit that you need");  
       if(choi_d_achat1_Button.getText().equalsIgnoreCase("رجوع"))
        message_envoi.setText("خطأ في تحويل  الرصيد ...نقودك اقل من الرصيد الذي طلبته");  
}


    Connection con;
    ResultSet rs_f , rs_kh;
    Statement st , st_2;
    int balance =0;
    static String Bank_Name;
    
public void  transaction_mtn_with_bank ()
{
 try {
   
       con = DriverManager.getConnection("jdbc:ucanaccess://Mtn_Atm_DB.mdb");
       
       st = con.createStatement();
       st_2 = con.createStatement();
       
       if(Bank_Name.equalsIgnoreCase("Faisal Bank"))
       {      rs_f = st.executeQuery("select * from Faisal_Bank where Account_number = "+account_number+" ;");
  
          while(rs_f.next())
            {
                System.out.println(rs_f.getInt("Balance"));
             if(rs_f.getInt("Balance") >= Integer.parseInt(montant_credi.getText()))
             {    balance = rs_f.getInt("Balance") - Integer.parseInt(montant_credi.getText());                               
                  reponse_positive_transfert();

                  System.out.println("on a passe");
             
                  this.setSize(690,700);
                 int test = st_2.executeUpdate("update Faisal_Bank set Balance ="+balance+" where Account_number = "+account_number+";" );                
             System.out.println("test="+test);
             }
             else reponse_negative_transfert();  

            }
 }
      if(Bank_Name.equalsIgnoreCase("Khartoum Bank"))
    {    rs_kh = st.executeQuery("select * from Khartoum_Bank where Account_number = "+account_number+" ;");
       while(rs_kh.next())
            {
                System.out.println(rs_kh.getInt("Balance"));
             if(rs_kh.getInt("Balance") >= Integer.parseInt(montant_credi.getText()))
             {    balance = rs_kh.getInt("Balance") - Integer.parseInt(montant_credi.getText());                               
                  reponse_positive_transfert();

                  System.out.println("on a passe");
             
                  this.setSize(690,700);
                 int test = st_2.executeUpdate("update Khartoum_Bank set Balance ="+balance+" where Account_number = "+account_number+";" );                
             System.out.println("test="+test);
             }
             else reponse_negative_transfert();  

            }
    }
 }catch(Exception er)
 { 
   JOptionPane.showMessageDialog(null,er);
 }
 
}

public void progression_bar_function(){
    
            t = new Timer (100,new ActionListener()
        {
            public void actionPerformed(ActionEvent ee)
        {   jb1.setVisible(true); 
               if(ii==100)
               {
                   t.stop();
                   
                   System.out.println("ii"+ii);
                   transaction_mtn_with_bank ();
             

               }else {
                   ii=ii+5;
                   jb1.setValue(ii);
               }
        }

        });
            System.out.println("iii_final"+ii);

}

public void no_mtn_number(){
     message_envoi.setText(null);  
            jPanel5.setVisible(true);
        
             if(choi_d_achat1_Button.getText().equalsIgnoreCase("Retour"))
             message_envoi.setText("C est pas un numero de MTN");
             if(choi_d_achat1_Button.getText().equalsIgnoreCase("Back"))
             message_envoi.setText("this is not a MTN number");  
             if(choi_d_achat1_Button.getText().equalsIgnoreCase("رجوع"))
             message_envoi.setText("هذا الرقم ليس اريبا");  
             
         montant_credi.setEditable(false);
}

}
